services:
- docker
matrix:
  include:
  - language: go
    go:
    - 1.11.x
    before_script:
    - mv ../../silenceper ../../xiaomi
    - cd ../../xiaomi/naftis
    script:
    - make fmt lint vet build.api
    - if [ -n "$TRAVIS_TAG" ]; then make docker.api docker.login push.api; fi
  - language: node_js
    node_js:
    - 8
    script:
    - make build.ui
    - if [ -n "$TRAVIS_TAG" ]; then make docker.ui docker.login push.ui; fi
before_deploy:
- make release
deploy:
  provider: releases
  file:
  - manifest.tar.gz
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: FWZaLrqb64r2FXPAbfVR0zCQ14IIskkl051fGcpiYWE1eObSUXWdfhHfreFl4vQw8OYd52XcbeeoVFdE9+51s5rUm87VDkdxlpAuZqi2TC43tNsC+FdFGhGfMnmUEPIQJyBt1T4REK5OpKOLvO7bJp3Dm0MNNDM5Jpwcy9aY9wVE6i+qsyRBQtMB/npR3OQPMzja/AeVrsiNg6sxbuQ+FPyQSW2a3oefcTBGj0GhEsOGQm9UDKPLRHx650KTVnRD5l1yftlbd32B7j400GnWoGBkhPWGLskh53srfRZofp3IUcxrQdr74qBI+D7ajnNn0lYlN5ltVscKHxTEjJmb0XSHPnp73QXm3LiS2+z6Ny0Pob36nGvlOFSs7whY3JQGMyJZuqvpqbIPuorJh02u4z542jxkLhZCPRQdhUmTafpTpK2Chd75q6njPMLTIIUj4OtzsIfc6PYAezEa7IYYA1/Co13bOx0hpjC0HX6cwn7PFdORYgNHpFqhYUnSVYqTfSPzHyLf8aDqiEpAjKFaY3d+I0tVBfEsnMejLTOrFUB7EDZ+U4N4/grZf2pwUOjTtf1uiPChBtF+pmn2uiRcI5iww6nfOPnBowVVkBO6p4MgCnf2LihKjqXg75R4I60pb5abwRP1vEeXJKXdqPMqC09VUQQF95sda1IEOS2RzV8=
env:
  global:
    HUB: silenceper
    DOCKER_USERNAME: silenceper
