services:
- docker
matrix:
  include:
  - language: go
    go:
    - 1.11.x
    before_script:
    - mv ../../silenceper ../../xiaomi
    - cd ../../xiaomi/naftis
    script:
    - make fmt lint vet build.api
    - if [ -n "$TRAVIS_TAG" ]; then make docker.api docker.login push.api; fi
  - language: node_js
    node_js:
    - 8
    script:
    - make build.ui
    - if [ -n "$TRAVIS_TAG" ]; then make docker.ui docker.login push.ui; fi
env:
  global:
    HUB: silenceper
    TRAVIS_TAG: dev
    DOCKER_USERNAME: silenceper
